# Site settings
title: L'Atelier de Floflo
SEOTitle: L'Atelier de Floflo
description: Retrouvez toutes mes créations couture sur ce blog !
keyword: "Retrouvez toutes mes créations couture sur ce blog !"
url: "https://jekyll-theme-gungnir.vercel.app"      # your host, for absolute URL
baseurl: ""                                         # for example, '/blog' if your blog hosted on 'host/blog'
avatar: "img/header-avatar.jpeg"                    # the avatar showing on the homepage


# GitHub repository (if the site is hosted by GitHub)
repository: nicohlr/l-atelier-de-floflo
repository_branch: main


# Theme style settings
theme_style:
  highlight:    # "dark" (default), "light"
  alert:        # "flat" (default), "modern"
  post_preview: # "image" (default), "text"
                # display post's featured image on homepage or not


# Markdown enhancements settings
math:
  enable:         # false (default), true
                  # math rendering for all posts and keynotes
  engine:         # "katex" (default), "mathjax"
                  # only make sense when `math.engine: true`
chart:            # false (default), true
mermaid: true     # false (default), true
emoji-plus: true  # false (default), true


# CDN settings
cdn:
  source:       # "jsdelivr" (default), "bootcdn", "unpkg", "cdnjs"
  enable:       # false (default), true
                # optimizing asset files via jsDelivr or not


# Publish posts or collection documents with a future date.
future: true

collections:
  experiences:
    output: true
  publications:
    output: true
  projects:
    output: true


# SNS settings
sns:
  RSS: true
  github_username: nicohlr
  linkedin_username: nicolashoulier
  email_address: nicolas.houlier@gmail.com


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  - package.json
  - package-lock.json
  - README.md
  - README-CN.md
  - LICENSE
  - Gruntfile.js
  - Gemfile
  - Gemfile.lock
  - /node_modules
anchorjs: true  # if you want to customize anchor. check out `anchor.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN


# Gems
# you have to `bundle config set path 'vendor/bundle' && bundle install` before local preview
plugins:
  - jekyll-paginate
  - jemoji


# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                       # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    disable: true                  # we use highlight.js for syntax highlighting, so we disable rouge here


# Navigation menu settings
menus:
  - title: Accueil
    font: fab fa-fort-awesome
    url: /
  - title: Posts
    font: fas fa-archive
    url: /posts/


# Comment settings
comment:
  provider:  # false (default), "disqus", "gitalk", "valine"

# Analytics settings
analytics:
  # Baidu Analytics
  ba_track_id:

  # Google Analytics
  ga_track_id:


# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true


# Whether or not to enable Hitokoto (the bubble on homepage)
hitokoto: true # default: false
