name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.13  # Specify the Ruby version you are using
          bundler-cache: true

      - name: Install theme
        run: bundle config set path 'vendor/bundle'

      - name: Install dependencies
        run: bundle install

      - name: Build the site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          publish_dir: ./_site